### PR TITLE
vig forked, vig commit cart update

### PR DESCRIPTION
**Pull request by Vigeza**
by vig account,
please accept my improved cart update

### CODE REVIEW

**Comment by karakasEnes** [comment]
next time please DO better

**Comment by Vigeza** [comment]
> next time please DO better

I will do my best sir

**Comment by Vigeza** [comment]
lşi,lş

**Comment by karakasEnes** [comment]
I think i liked it i will change my mind maybe

**Comment by Vigeza** [comment]
> nk i liked it i w

thank u sir

**Pull request merged**
